# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b989a4dee50ce93bf3477191eeb1748c7974ecc1d78f80e3066b30a33fe6de5453995b878a384acc6bbaa105203a0dbaebd3502d7d467a1f8d6a18fef83a0799

test:
  secret_key_base: b4784677d3eec3a0b4f202d698f6f1e902df3ce0f31091cf21198ff00d2e6914e0edd3b61decbdcf7becdfd9755d1e98c709be40f2127cbff7d09065c53f4101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
